<a href="https://colab.research.google.com/github/capricode-ui/AIML-Projects/blob/main/CosineSimilarity2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from transformers import AutoTokenizer, AutoModel
import torch
#Importing the tokenizer and model class from transformer library

In [ ]:
tokenizer = AutoTokenizer.from_pretrained('sentence-transformers/all-mpnet-base-v2')
model = AutoModel.from_pretrained('sentence-transformers/all-mpnet-base-v2')
#tokenizer and model was downloaded from hugging face

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/438M [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()


In [ ]:
example_sentence = 'its a sunny morning'
example_tokens = tokenizer.encode_plus(example_sentence, max_length = 512, truncation = True, padding = 'max_length', return_tensors = 'pt' )
example_tokens.keys()
#irrelevant to the overall code structure

NameError: name 'tokenizer' is not defined

 Answers to a sample question in the dataset



In [ ]:
"""

sentences = [

             "Dynamic scaling refers to the evolution of self-similar systems, where data obtained from snapshots at fixed times exhibits similarity to the respective data taken from snapshots of any earlier or later time. This similarity is tested by a certain time-dependent stochastic variable x.","Dynamic scaling refers to the non-evolution of self-similar systems, where data obtained from snapshots at fixed times is similar to the respective data taken from snapshots of any earlier or later time. This similarity is tested by a certain time-dependent stochastic variable x.","Dynamic scaling refers to the evolution of self-similar systems, where data obtained from snapshots at fixed times is dissimilar to the respective data taken from snapshots of any earlier or later time. This dissimilarity is tested by a certain time-independent stochastic variable y.","Dynamic scaling refers to the non-evolution of self-similar systems, where data obtained from snapshots at fixed times is dissimilar to the respective data taken from snapshots of any earlier or later time. This dissimilarity is tested by a certain time-independent stochastic variable y.","Dynamic scaling refers to the evolution of self-similar systems, where data obtained from snapshots at fixed times is independent of the respective data taken from snapshots of any earlier or later time. This independence is tested by a certain time-dependent stochastic variable z.",

]


sentences=[
    "Regularizing the mass-energy of an electron with a finite radius can theoretically simplify calculations involving infinities or singularities, thereby providing explanations that would otherwise be impossible to achieve.","Regularizing the mass-energy of an electron with an infinite radius allows for the breakdown of a theory that is valid under one set of conditions. This approach can be applied to other renormalization problems as well.,Regularizing the mass-energy of an electron with a finite radius is a means of demonstrating that a system below a certain size can be explained without the need for further calculations. This approach can be applied to other renormalization problems as well.","Regularizing the mass-energy of an electron with an infinite radius can be used to provide a highly accurate description of a system under specific conditions. This approach can be transferred to other renormalization problems as well.","Regularizing the mass-energy of an electron with an infinite radius is essential for explaining how a system below a certain size operates. This approach can be applied to other renormalization problems as well."
]

"""

sentences=[
    "The triskeles symbol was reconstructed as a feminine divine triad by the rulers of Syracuse, and later adopted as an emblem. Its usage may also be related to the Greek name of Sicily, Trinacria, which means ""having three headlands."" The head of Medusa at the center of the Sicilian triskeles represents the three headlands.","The triskeles symbol is a representation of three interlinked spirals, which was adopted as an emblem by the rulers of Syracuse. Its usage in modern flags of Sicily has its origins in the ancient Greek name for the island, Trinacria, which means ""Sicily with three corners."" The head of Medusa at the center is a representation of the island's rich cultural heritage.","The triskeles symbol is a representation of a triple goddess, reconstructed by the rulers of Syracuse, who adopted it as an emblem. Its significance lies in the fact that it represents the Greek name for Sicily, Trinacria, which contains the element ""tria,"" meaning three. The head of Medusa at the center of the Sicilian triskeles represents the three headlands.","The triskeles symbol represents three interlocked spiral arms, which became an emblem for the rulers of Syracuse. Its usage in modern flags of Sicily is due to the island's rich cultural heritage, which dates back to ancient times. The head of Medusa at the center represents the lasting influence of Greek mythology on Sicilian culture.","The triskeles symbol is a representation of the Greek goddess Hecate, reconstructed by the rulers of Syracuse. Its adoption as an emblem was due to its cultural significance, as it represented the ancient Greek name for Sicily, Trinacria. The head of Medusa at the center of the Sicilian triskeles represents the island's central location in the Mediterranean."

]
#sentences which are to be processed for cosine similarity

In [ ]:
tokens = {'input_ids': [], 'attention_mask': [] }

for sentence in sentences:
    new_tokens = tokenizer.encode_plus(sentence, max_length = 512, truncation = True, padding = 'max_length', return_tensors = 'pt' )
    tokens['input_ids'].append(new_tokens['input_ids'][0])
    tokens['attention_mask'].append(new_tokens['attention_mask'][0])

# restructure a list of tensors into single tensor
tokens['input_ids'] = torch.stack(tokens['input_ids'])
tokens['attention_mask'] = torch.stack(tokens['attention_mask'])

In [ ]:
tokens['attention_mask']

tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]])

In [ ]:
outputs = model(**tokens)
outputs

BaseModelOutputWithPooling(last_hidden_state=tensor([[[ 8.1261e-02, -3.8535e-01, -1.1094e-01,  ...,  2.2897e-02,
           8.0473e-02, -3.6694e-02],
         [ 1.4462e-01, -6.2237e-01, -2.0745e-01,  ..., -3.2335e-02,
           8.0157e-02,  5.4949e-02],
         [ 1.2681e-01, -8.3219e-01, -5.6564e-02,  ...,  1.3216e-01,
           2.5443e-02,  6.9835e-02],
         ...,
         [ 1.1222e-01, -3.1861e-01, -1.1745e-01,  ...,  1.1792e-02,
           7.6605e-02,  8.6306e-03],
         [ 1.1222e-01, -3.1861e-01, -1.1745e-01,  ...,  1.1792e-02,
           7.6605e-02,  8.6306e-03],
         [ 1.1222e-01, -3.1861e-01, -1.1745e-01,  ...,  1.1792e-02,
           7.6605e-02,  8.6306e-03]],

        [[ 1.1109e-01, -3.8754e-01, -7.4494e-02,  ...,  1.4285e-02,
           6.9957e-02,  6.5965e-03],
         [ 1.8309e-01, -6.7927e-01, -1.5333e-01,  ...,  7.9888e-03,
           6.7997e-02,  1.0110e-01],
         [ 1.4960e-01, -8.2920e-01, -3.9345e-02,  ...,  1.4514e-01,
           2.6434e-02,  7.9526e

In [ ]:
outputs.keys()

odict_keys(['last_hidden_state', 'pooler_output'])

In [ ]:
embeddings = outputs.last_hidden_state
embeddings

tensor([[[ 8.1261e-02, -3.8535e-01, -1.1094e-01,  ...,  2.2897e-02,
           8.0473e-02, -3.6694e-02],
         [ 1.4462e-01, -6.2237e-01, -2.0745e-01,  ..., -3.2335e-02,
           8.0157e-02,  5.4949e-02],
         [ 1.2681e-01, -8.3219e-01, -5.6564e-02,  ...,  1.3216e-01,
           2.5443e-02,  6.9835e-02],
         ...,
         [ 1.1222e-01, -3.1861e-01, -1.1745e-01,  ...,  1.1792e-02,
           7.6605e-02,  8.6306e-03],
         [ 1.1222e-01, -3.1861e-01, -1.1745e-01,  ...,  1.1792e-02,
           7.6605e-02,  8.6306e-03],
         [ 1.1222e-01, -3.1861e-01, -1.1745e-01,  ...,  1.1792e-02,
           7.6605e-02,  8.6306e-03]],

        [[ 1.1109e-01, -3.8754e-01, -7.4494e-02,  ...,  1.4285e-02,
           6.9957e-02,  6.5965e-03],
         [ 1.8309e-01, -6.7927e-01, -1.5333e-01,  ...,  7.9888e-03,
           6.7997e-02,  1.0110e-01],
         [ 1.4960e-01, -8.2920e-01, -3.9345e-02,  ...,  1.4514e-01,
           2.6434e-02,  7.9526e-02],
         ...,
         [ 1.1984e-01, -4

In [ ]:
pooled = outputs.pooler_output
pooled.shape

torch.Size([5, 768])

In [ ]:
embeddings.shape

torch.Size([5, 512, 768])

In [ ]:
attention_mask = tokens['attention_mask']
attention_mask.shape

torch.Size([5, 512])

In [ ]:

resized_attention_mask = attention_mask.unsqueeze(-1).expand(embeddings.size()).float()
resized_attention_mask.shape

torch.Size([5, 512, 768])

In [ ]:
resized_attention_mask

tensor([[[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 

In [ ]:

resized_attention_mask[0][0].shape

torch.Size([768])

In [ ]:
masked_embedding = embeddings * resized_attention_mask
masked_embedding.shape

torch.Size([5, 512, 768])

In [ ]:

masked_embedding

tensor([[[ 8.1261e-02, -3.8535e-01, -1.1094e-01,  ...,  2.2897e-02,
           8.0473e-02, -3.6694e-02],
         [ 1.4462e-01, -6.2237e-01, -2.0745e-01,  ..., -3.2335e-02,
           8.0157e-02,  5.4949e-02],
         [ 1.2681e-01, -8.3219e-01, -5.6564e-02,  ...,  1.3216e-01,
           2.5443e-02,  6.9835e-02],
         ...,
         [ 0.0000e+00, -0.0000e+00, -0.0000e+00,  ...,  0.0000e+00,
           0.0000e+00,  0.0000e+00],
         [ 0.0000e+00, -0.0000e+00, -0.0000e+00,  ...,  0.0000e+00,
           0.0000e+00,  0.0000e+00],
         [ 0.0000e+00, -0.0000e+00, -0.0000e+00,  ...,  0.0000e+00,
           0.0000e+00,  0.0000e+00]],

        [[ 1.1109e-01, -3.8754e-01, -7.4494e-02,  ...,  1.4285e-02,
           6.9957e-02,  6.5965e-03],
         [ 1.8309e-01, -6.7927e-01, -1.5333e-01,  ...,  7.9888e-03,
           6.7997e-02,  1.0110e-01],
         [ 1.4960e-01, -8.2920e-01, -3.9345e-02,  ...,  1.4514e-01,
           2.6434e-02,  7.9526e-02],
         ...,
         [ 0.0000e+00, -0

In [ ]:
summed_masked_embeddings = torch.sum(masked_embedding, 1)
summed_masked_embeddings.shape

torch.Size([5, 768])

In [ ]:

summed_masked_embeddings

tensor([[  8.9733, -30.1590,  -8.2105,  ...,   0.7942,   5.2706,   0.2227],
        [ 10.7903, -35.7296,  -8.1999,  ...,  -2.2557,   4.4518,   2.4432],
        [  9.8141, -33.1844,  -8.6742,  ...,   2.5165,   3.6744,   1.5743],
        [  5.8534, -27.5625,  -7.6366,  ...,  -1.7102,   2.5608,   2.5240],
        [ 11.0374, -29.8491,  -6.6267,  ...,   1.4834,   9.4139,   2.5497]],
       grad_fn=<SumBackward1>)

In [ ]:

resized_attention_mask

tensor([[[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 

In [ ]:
count_of_one_in_mask_tensor = torch.clamp(resized_attention_mask.sum(1), min=1e-9 )

count_of_one_in_mask_tensor.shape

torch.Size([5, 768])

In [ ]:

count_of_one_in_mask_tensor

tensor([[71., 71., 71.,  ..., 71., 71., 71.],
        [80., 80., 80.,  ..., 80., 80., 80.],
        [78., 78., 78.,  ..., 78., 78., 78.],
        [69., 69., 69.,  ..., 69., 69., 69.],
        [75., 75., 75.,  ..., 75., 75., 75.]])

In [ ]:

summed_masked_embeddings.shape

torch.Size([5, 768])

In [ ]:

count_of_one_in_mask_tensor.shape

torch.Size([5, 768])

In [ ]:
mean_pooled = summed_masked_embeddings / count_of_one_in_mask_tensor

In [ ]:
mean_pooled.shape

torch.Size([5, 768])

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

mean_pooled = mean_pooled.detach().numpy()

cosine_similarity([mean_pooled[0]], mean_pooled[1:] )

array([[0.922446  , 0.9616895 , 0.89386415, 0.89291   ]], dtype=float32)